# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7abc36dcdf8f4c196ec46e53160501d428b97f631948dfeeeed714a8fcbc3afc268653128acd5ad0c7d6d625701ea04590f6740f070404d0bf86495c51281845

test:
  secret_key_base: 89a5d58a2e9f4fe1759bbbb098e579a084ed995ee2a34746eaefc0f1da15303ea9efc4f4a38824b23d661643a7023caed9c552db4404e2fcf0eff202b475e34c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
